[package]
name = "rrv-core"
version.workspace = true
edition.workspace = true

[dependencies]
nom.workspace = true
log.workspace = true
glam.workspace = true
strum.workspace = true
strum_macros.workspace = true
